image: '$IMAGE_URL'
stages:
  - lint
  - build
  - deploy
  - release

lint:php:
  stage: lint
  script:
    - parallel-lint .
  tags:
    - k8s

lint:php-codestyle:
  stage: lint
  script:
    - php-cs-fixer fix -v --dry-run --using-cache=no . --config .php_cs.dist
  tags:
    - k8s

lint:composer:
  stage: lint
  script:
    - composer validate --no-interaction --strict
  tags:
    - k8s

lint:secretsscan:
  image: '$IMAGE_URL_PYTHON'
  stage: lint
  script:
    - ci/scan_secrets.sh
  tags:
    - k8s

build:phar:
  stage: build
  script:
    - composer install --no-dev --no-interaction --no-progress
    - curl -L --output /tmp/box.phar https://github.com/humbug/box/releases/download/3.8.4/box.phar
    - chmod +x /tmp/box.phar
    - /tmp/box.phar compile
  artifacts:
    expire_in: 1 hour
    paths:
      - tipctl.phar
  tags:
    - k8s

deploy:create-github-deploy:
  stage: deploy
  only:
    - tags
  script:
    - ci/sync_to_github.sh
  tags:
    - k8s

release:create-github-release:
  stage: release
  only:
    - tags
  except:
    - merge_requests
  script:
    - ci/release_to_github.sh $CI_COMMIT_TAG ./tipctl.phar
  tags:
    - k8s
